### PR TITLE
Banner creation

### PR DESCRIPTION
**Pull request by remingtr**
Made the banner a layout file.  

To use the layout use import Layout from '../banner-layout.svelte' in the script tag on a .svelte file

Then use a Layout tag just like the /routes/events/+page.svelte file

These changes are visible on the /events page if you 
1. Use supabase start with docker open to get local instance running
2. cd into src-web-app and use npm run dev
3. Sign in using amy@testuser.com password damfit
4. Banner will be visible on left side of screen and the logout button is on the top middle of the screen

### CODE REVIEW

**Review by adulbrich — APPROVED** [review]
Well done. In the future we will need to optimize images, maybe creating an SVG instead because it's a lot of bandwidth.

**Review by adulbrich — CHANGES_REQUESTED** [review]
Why not using `+layout.svelte`? So that you avoid importing the layout?

https://learn.svelte.dev/tutorial/layouts

Edit: you're correct that the root layout applies to every route and we don't want it on the `/auth` route

**Review by adulbrich — APPROVED** [review]

**Comment by fuenteed** [comment]
Code all looks good and ready to be deployed for the rest of the pages.

**Review by fuenteed — APPROVED** [review]
The code looks good and ready to be merged

**Pull request merged**
