### PR TITLE
Add email based auth to web application

### PR DESCRIPTION
**Pull request by traveno**
This fulfills the web app portion of #32

The application redirects to `/auth` if no user session exists.
If a user session exists, the application redirects to `/events` by default.

A basic error message is displayed above the login form.

### CODE REVIEW

**Review by aidanwroos — COMMENTED** [review]
Error when building "src-web-app"

Screenshot 2023-11-16 092340

**Comment by remingtr** [comment]
I successfully tested this pull request and verified my email, but there were some details that should be included in the README or commit message.  The .env file contents should be included somewhere in the readme, or the file should be tracked instead.  It would also be nice if there were some comments at the top of each modified file so we know what each file does.  I would imagine that it would be tough to debug this code on our own if we didn't know which file to look for in the future. But overall the file structure was easy to understand and I think it will create a great foundation once more documentation is included.

**Comment by traveno** [comment]
Thanks Ryan! Yes, I forgot to mention that an `.env` file is needed inside `/src-web-app/`, please refer to Discord for the file contents.

**Comment by traveno** [comment]
I'm closing this PR because #49 implements all changes from this branch and expands upon it.

**Pull request closed without merging**
