### PR TITLE
Bring the react-native concept project into /src-mobile-app

### LINKED ISSUE #14: Initialize mobile app
See results from #3 

Include proper README to get the team started

/src-mobile-app

Might be already taken care of: https://github.com/OregonStateUniversity/osu-fsf/tree/rn-concept

### PR DESCRIPTION
**Pull request by traveno**
Closes #14

### CODE REVIEW

**Review by adulbrich — APPROVED** [review]
Great job

**Review by LeiSun1226 — APPROVED** [review]
Works on my local environment

**Comment by LeiSun1226** [comment]
1. When the npm start, there was a function called "open debugger." If you press j. It will start launch and shows opening JavaScript... It requires Hermes Engine to be configured, but I'm not sure we need it (https://docs.expo.dev/guides/using-hermes/).
2. maybe can put more information in the README to explain how to run the app

**Comment by chungyu1108** [comment]
Work on my local machine

**Comment by aidanwroos** [comment]
Works on my local machine

**Review by fuenteed — COMMENTED** [review]
Works on my local machine

**Pull request merged**
