### PR TITLE
web page fix alignment

### PR DESCRIPTION
**Pull request by LeiSun1226**
fix create event page alignment, bars in the same length and width

### CODE REVIEW

**Review by traveno — APPROVED** [review]
Looks good!

**Review by traveno — CHANGES_REQUESTED** [review]
Do you mind looking at this again? There's some code that is out of scope for alignment. The create / edit event page doesn't look correct.

**Review by traveno — APPROVED** [review]
Approved! The odd styles on create / edit event are only the case in dark mode browsers. Light / dark styles for the web app are out of scope.

**Review by remingtr — APPROVED** [review]
Looks good.  The dark and light mode configurations can be changed later

**Pull request merged**
