### PR TITLE
View Step Count Leaderboard (Team)

### PR DESCRIPTION
**Pull request by LeiSun1226**
working on leaderboard

### CODE REVIEW

**Comment by LeiSun1226** [comment]
.deploy noop

**Comment by LeiSun1226** [comment]
.deploy noop

**Comment by remingtr** [comment]
Can you be more descriptive in your PR?  I would like to know what changes I should be seeing in the application when I test your pull request.  I can look at your commit history to see what files you have changed but it makes life a lot harder if I have to piece together what you are working on by myself.

**Comment by remingtr** [comment]
It's not a perfect example but this PR comment is pretty descriptive and should point someone in the right direction if they were reviewing it, and it shows people the steps to take to test the pull request.  

https://github.com/OregonStateUniversity/osu-fsf/pull/62#issue-2017856029

**Pull request closed without merging**
